version: '2'

services:

  build:
    image: urs-build
    build:
      context: ../
      dockerfile: ./Docker/Dockerfile-Mono-Build
    volumes:
      - artifact:/artifact

  app:
    image: mono:latest
    ports:
      - "8090:8090"
    volumes:
      - artifact:/artifact
    depends_on:
      - build
      - db
      - flyway-migrator
    working_dir: /artifact
    command: [ mono,  /artifact/UniversityRegistrationSystem.exe ]

  db:
    image: postgres:9.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=secret

  flyway-migrator:
    image: urs-flyway-migrator
    build:
      context: ../
      dockerfile: ./Docker/Dockerfile-Flyway
    volumes:
      - ./PostgresMigrations:/flyway/sql
    depends_on:
      - db
    entrypoint: /scripts/wait-for-postgres-for-flyway.sh db postgres postgres secret 
    
volumes:
  artifact:
    driver: local
